name: 'Submodule Notify Parent'

on:
  push:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    name: 'Submodule Update Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: murapix/murapix.github.io
        token: ${{ secrets.CI_TOKEN }}
    - name: Pull & Update Submodules Recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Commit
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git add --all
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
    
